[font]
size = 9.0
normal = {family = "Liberation Mono", style = "Regular"}

[window]
decorations = "full"
startup_mode = "Maximized"
#opacity = 0.95

[general]
import = [
  "~/.config/alacritty/monokai.toml"
]
