[font]
size = 10.0
normal = {family = "Liberation Mono", style = "Regular"}

[window]
decorations = "full"
opacity = 0.85
startup_mode = "Maximized"

[general]
import = [
  "~/.config/alacritty/monokai.toml"
]
